# This is a basic workflow to help you get started with Actions

name: Deploy React App

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Install Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12

    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
        
    - name: Build React App
      run: yarn build
        
    - name: Install Surge
      run: npm install -g surge
        
    - name: Deloy on surge
      run: surge ./build shoe_store_app_by_murtaza.surge.sh --token ${{ secrets.SURGE_TOKEN }}
